version: '3.7'

services:
  app:
    container_name: laravelteszt-app
    image: webdevops/php-nginx:7.3
    volumes:
      - ./:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      APP_NAME: LaravelTeszt
      APP_ENV: local
      DB_HOST: laravelteszt-database
      DB_PORT: 3306
      DB_DATABASE: laravelteszt
      DB_USERNAME: laravelteszt
      DB_PASSWORD: laravelteszt
    ports:
      - 8080:80
  database:
    container_name: laravelteszt-database
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=laravelteszt
      - MYSQL_USER=laravelteszt
      - MYSQL_PASSWORD=laravelteszt
    volumes:
      - my-datavolume2:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
    my-datavolume2:
